'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GOVCERT_Outlook_Addins.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property gcnotify() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("gcnotify", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GOVCERT_RGB_for_outlook_48_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOVCERT_RGB_for_outlook_48_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Please add your inquiry here].
        '''</summary>
        Friend ReadOnly Property NewMailBody() As String
            Get
                Return ResourceManager.GetString("NewMailBody", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit your message and then click &quot;send&quot; to send this email..
        '''</summary>
        Friend ReadOnly Property NewResendError() As String
            Get
                Return ResourceManager.GetString("NewResendError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SOC Request.
        '''</summary>
        Friend ReadOnly Property NewSubject() As String
            Get
                Return ResourceManager.GetString("NewSubject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Select at least one email to send..
        '''</summary>
        Friend ReadOnly Property NoSelectionError() As String
            Get
                Return ResourceManager.GetString("NoSelectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have entered a text in this Mail.
        '''
        ''' By accepting your message will be alterd..
        '''</summary>
        Friend ReadOnly Property OverWriteConfirm() As String
            Get
                Return ResourceManager.GetString("OverWriteConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please click &quot;send&quot; to send this email..
        '''</summary>
        Friend ReadOnly Property ResendError() As String
            Get
                Return ResourceManager.GetString("ResendError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The email from: 
        '''
        '''{{emailAddress}}
        '''
        '''with the subject
        '''
        '''{{emailSubject}}
        '''
        '''was already detected as SPAM.
        '''
        '''Do you realy want to send this email to GOVCERT?.
        '''</summary>
        Friend ReadOnly Property SPAMDialogText() As String
            Get
                Return ResourceManager.GetString("SPAMDialogText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dear GOVCERT,
        '''
        '''I want to forward the following emails to be analysed, as I found they look souspicious.
        '''
        '''Attachment(s):
        '''{{attachments}}
        '''
        '''With best regards,
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property SuspectBody() As String
            Get
                Return ResourceManager.GetString("SuspectBody", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [SUSPECT].
        '''</summary>
        Friend ReadOnly Property SuspectTag() As String
            Get
                Return ResourceManager.GetString("SuspectTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [GC-OBT].
        '''</summary>
        Friend ReadOnly Property Tag() As String
            Get
                Return ResourceManager.GetString("Tag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to soc@govcert.etat.lu.
        '''</summary>
        Friend ReadOnly Property These() As String
            Get
                Return ResourceManager.GetString("These", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1.4.0.
        '''</summary>
        Friend ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
